## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *
from eudplib.core.eudfunc import EUDTraceLog, EUDTracedFunc, EUDTracedTypedFunc, EUDTracedMethod, EUDTracedTypedMethod
from eudplib.epscript.helper import _RELIMP, _TYGV, _TYSV, _TYLV, _CGFW, _ARR, _VARR, _SRET, _SV, _ATTW, _ARRW, _ATTC, _ARRC, _L2V, _LSH, _ALL
# (Line 1) import PluginVariables as msqcvar;
import PluginVariables as msqcvar
# (Line 2) import Core;
import Core
# (Line 3) import Modules.GTA_TitleScreen as Title;
from Modules import GTA_TitleScreen as Title
# (Line 4) import Modules.GTAintro as Intro;
from Modules import GTAintro as Intro
# (Line 6) const displaytext = StringBuffer();
displaytext = _CGFW(lambda: [StringBuffer()], 1)[0]
# (Line 7) const	      layer = EUDArray(6);
layer = _CGFW(lambda: [EUDArray(6)], 1)[0]
# (Line 11) function beforeTriggerExec(){
@EUDFunc
def beforeTriggerExec():
    # (Line 15) foreach(player : EUDLoopPlayer()) {
    for player in EUDLoopPlayer():
        # (Line 18) if(msqcvar.VKeyDown_F[player]){ CreateUnit(1,8,248,0);}
        if EUDIf()(msqcvar.VKeyDown_F[player]):
            DoActions(CreateUnit(1, 8, 248, 0))
            # (Line 19) if(msqcvar.VKeyDown_W[player]){}
        EUDEndIf()
        if EUDIf()(msqcvar.VKeyDown_W[player]):
            # (Line 20) if(msqcvar.VKeyDown_A[player]){}
            pass
        EUDEndIf()
        if EUDIf()(msqcvar.VKeyDown_A[player]):
            # (Line 21) if(msqcvar.VKeyDown_S[player]){}
            pass
        EUDEndIf()
        if EUDIf()(msqcvar.VKeyDown_S[player]):
            # (Line 22) if(msqcvar.VKeyDown_D[player]){}
            pass
        EUDEndIf()
        if EUDIf()(msqcvar.VKeyDown_D[player]):
            # (Line 23) if(msqcvar.VKeyDown_F[player]){}
            pass
        EUDEndIf()
        if EUDIf()(msqcvar.VKeyDown_F[player]):
            # (Line 24) if(msqcvar.VKeyDown_F[player]){}
            pass
        EUDEndIf()
        if EUDIf()(msqcvar.VKeyDown_F[player]):
            # (Line 25) if(msqcvar.VKeyDown_F[player]){}
            pass
        EUDEndIf()
        if EUDIf()(msqcvar.VKeyDown_F[player]):
            # (Line 30) if(Title.DrawGTA() <=1302){ Title.DrawGTA(); Core.LoadingScreen( player ,(Title.DrawGTA()*100)/1302);}
            pass
        EUDEndIf()
        if EUDIf()(Title.DrawGTA() <= 1302):
            Title.DrawGTA()
            Core.LoadingScreen(player, (Title.DrawGTA() * 100) // 1302)
            # (Line 31) else{Intro.beforeTriggerExec();}
        if EUDElse()():
            Intro.beforeTriggerExec()
            # (Line 32) if(Title.DrawGTA() ==1302){Core.TextRefresh(player);}
        EUDEndIf()
        if EUDIf()(Title.DrawGTA() == 1302):
            Core.TextRefresh(player)
            # (Line 36) }
        EUDEndIf()
        # (Line 45) }

    # (Line 47) function onPluginStart(){

@EUDFunc
def onPluginStart():
    # (Line 49) }
    # (Line 50) function afterTriggerExec(){
    pass

@EUDFunc
def afterTriggerExec():
    # (Line 52) }
    pass
